name: Weekly Builds of KeY

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # every monday morning


permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

env:
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Generated Stubs, Documentation and Assemble
        run: ./gradlew --parallel :keyext.api.doc:run
      - run: ./gradlew --parallel :dokkaGeneratePublicationHtml assemble

      - run: cp -R build/dokka/html/ out/dokka
      - run: ls -lR out

      - name: "Upload GitHub Pages artifact"
        uses: actions/upload-pages-artifact@v5
        with:
          path: out/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      - name: Delete previous nightly release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly --yes --cleanup-tag 

      - name: Create nightly release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #--notes-start-tag KEY-2.12.3 \
        run: |
          gh release create --generate-notes --title "Nightly Release" \
             --prerelease nightly */build/libs/*-all.jar */build/distributions/keyext.api.app.zip

#      - name: Upload to SNAPSHOT repository
#        run: ./gradlew --parallel publishMavenJavaPublicationToKEYLABRepository
#        env:
#          BUILD_NUMBER: "SNAPSHOT"
#          GITLAB_DEPLOY_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}
#          SIGNING_KEY_ID: ${{secrents.SIGNING_KEY_ID}}
#          GPG_PRIVATE_KEY: ${{secrents.GPG_PRIVATE_KEY}}
#          GPG_PASSPHRASE: ${{secrents.GPG_PASSPHRASE}}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
